### PR TITLE
Modified Azure Theme

### PR DESCRIPTION
**Pull request by psDevUK**
Fixed some more request from the previous update I provided. now dividers are themed, sub-menu themed, links on cards themed and the background pagination colour. If anyone has anything I havent modified, let me know

### CODE REVIEW

**Comment by sk82jack** [comment]
@psDevUK looking good man. Wanted to point out two more issues then I'm happy 😅

Maybe we can make the font white or black on the active grid page. Can't really see the number as it is:
image


And subheaders are still hard to see (inbetween My First Page and My Second Page in the screenshot below):
image

**Comment by psDevUK** [comment]
@sk82jack I got no problems changing those last requests, can you please chuck the code you are using to generate your sub-headers as I havent used that before...looks like I need to adjust the font size to, bring it in line with the others, will actually test this on a grid this time with pagination, will close this pull request and re-do it later. Thanks

**Comment by psDevUK** [comment]
@sk82jack I will figure the sub heading menu as mentioned I will close for now then open a new pull request later once those last two items have been changed. I will double check all components....would like to make border white on radio buttons when selected, as it looks like its green at the moment, anyways I will tinker some more then upload later. Peace.

**Comment by sk82jack** [comment]
@psDevUK I just used the example from the docs here https://docs.universaldashboard.io/components/navigation#including-dividers-and-subheaders

And for future reference - you can leave a PR open and keep pushing commits to it and it will automatically update the PR for you. In that sort of situation it's usually advised to change the title to include `WIP:` at the start (stands for Work In Progress) so that it doesn't get merged early by accident or something 🙂

**Pull request closed without merging**
