### PR TITLE
Reduce main bundle size.

### LINKED ISSUE #411: Code Splitting
Should introduce webpack code splitting to reduce the size of the bundle. The bundle has reached over 2 MB. If a control isn't used, it should't be loaded. 

https://webpack.js.org/guides/code-splitting/

### PR DESCRIPTION
**Pull request by adamdriscoll**
This reduces the main bundle size from about 2.5 MB to 650 KB via code-splitting in webpack. Still would like to get it down past the recommended size (244KB).

This also fixes the source maps. 

Fixes #411

### CODE REVIEW

**Comment by AlonGvili** [comment]
main.6e7edc06572783021524.bundle.js (659 KiB) 
I think you did it 👍

**Comment by adamdriscoll** [comment]
Something is not quite right. The integration tests are failing. Looking into it now. But if it works it would load much faster!

**Comment by AlonGvili** [comment]
> Something is not quite right. The integration tests are failing. Looking into it now. But if it works it would load much faster!

Yes you right I watching the build and did not understand why its stop running :)

**Comment by AlonGvili** [comment]
I manage to make it work with react. lazy 
[Build status](https://ci.appveyor.com/project/AlonGvili/universal-dashboard)

I was working on a build before you release all the latest fixes to the tests, so you are going to see some red lines 😞

**Pull request closed without merging**
