### PR TITLE
Fixes #748

### LINKED ISSUE #748: Upload files via REST API
We need to support something like this. 

```
Invoke-RestMethod -Uri $uri -Method Post -InFile $uploadPath -UseDefaultCredentials
```

In ASP.NET Core, you can upload a file by accepting IFormFile. 

https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2

UD is a little different because it does it's own routing. This is where we would implement the code to accept the file somehow. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Controllers/ComponentController.cs#L440

I think we will have to see if we can process the body as a file somehow here: 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Controllers/ComponentController.cs#L449

We might need to add a parameter to New-UDEndpoint to specify that this endpoint accepts a file rather than a form body.

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Cmdlets/NewEndpointCommand.cs

### PR DESCRIPTION
**Pull request by BoSen29**
Allows for file upload via REST -api.
Note: the original file name is not included in the request. 
However, added support for "wildcard" contenttype: ie: file/* and image/* in order to reconstruct. 
Readable from the HTTP Request in Endpoint. 

See 
https://hastebin.com/tediyiqahi.bash 
for Powershell Example.

For uploading files -contenttype must be specified according to pattern.

### CODE REVIEW

**Comment by BoSen29** [comment]
Phew! 
I'll open a cold one in anticipation!

**Comment by adamdriscoll** [comment]
@BoSen29 Can you run the API tests on your box? D:\a\1\s\src\UniversalDashboard.UITest\Integration\Api.Tests.ps1 

It looks like it's throwing a 500 on 3 of the tests which indicate an unhandled exception is being thrown.

**Comment by BoSen29** [comment]
@adamdriscoll the tests fail, however when i try to replicate the tests it works great. 
This is when i copy the code from the test, including the endpoints and the invoke-restmethod commands. 
I'll have to look into as to why the automatic tests fail :O

**Comment by BoSen29** [comment]
@adamdriscoll 
Can't see anything relevant by enable logging on the tests either. 
I'll give it a go in the morning!

**Comment by adamdriscoll** [comment]
I can pull down this branch and give er a shot too to see if I have any ideas.

**Comment by BoSen29** [comment]
@adamdriscoll found the issue, the check for contenttype failed if the request was done in a "delete" manner. 
Simple check for method solved it.

**Comment by BoSen29** [comment]
Added an enhancement request for future improvements. 
#1262
I'll look into it, and should probably be fixed before 2.7 :-)

**Comment by adamdriscoll** [comment]
Awesome! Yeah that looks good!

**Pull request merged**
