### PR TITLE
Fix for #134

### PR DESCRIPTION
**Pull request by oitptobbe**
This will add support for changing the placeholder for the filter box when not using server side processing.

### CODE REVIEW

**Comment by oitptobbe** [comment]
This will also solve "Unable to adjust New-UDImageCarousel container height when *not* using the -FullWidth switch" issue.

**Comment by adamdriscoll** [comment]
LGTM! Thanks!

**Comment by adamdriscoll** [comment]
Please make sure to claim both bounties! I closed both related issues so you should be able to click Claim Bounty on bounty source to have at it.

**Comment by oitptobbe** [comment]
Yeah.

Med vänliga hälsningar,

Tobias Fredriksson
IT-Magiker

23 aug. 2019 kl. 17:40 skrev Adam Driscoll <notifications@github.com>:

﻿

Please make sure to claim both bounties! I closed both related issues so you should be able to click Claim Bounty on bounty source to have at it.

**Pull request merged**
