### PR TITLE
Add title-alignment to card

### LINKED ISSUE #518: Add -TitleAlignment Param to New-UDCard
Add ability to align the Title of a Card

Added this to my local module and works great

[ValidateSet('left', 'center', 'right')]        
[String]$TitleAlignment = 'left',

Then within the span element added $TitleAlignment to className

image

### PR DESCRIPTION
**Pull request by BoSen29**
Fixes / closes #518

### CODE REVIEW

**Comment by adamdriscoll** [comment]
This pull request has been mentioned on **PowerShell Universal Dashboard Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/add-titlealignment-param-to-new-udcard-518/1425/2

**Comment by adamdriscoll** [comment]
Change looks good. Can you update the test for this? It's check for "card-title". Just needs to check for "card-title left-align "

Expected string length 11 but was 22. Strings differ at index 11.
Expected: {card-title }
But was: {card-title left-align }
----------------------^

at line: 35 in D:\a\1\s\src\UniversalDashboard.UITest\Cmdlet\New-UDCard.Tests.ps1
35:         (New-UDCard -Title "title").Content[0].Content[0].Attributes.className | Should be "card-title "

**Comment by BoSen29** [comment]
So yeah, no idea how to add files to existing PR, so i made another PR with the required change :-)

**Comment by adamdriscoll** [comment]
Haha. That works for me. You can always make more changes to you existing branch and then push them and it will update the PR.

**Comment by adamdriscoll** [comment]
@BoSen29 - If you click claim on this bounty, I can send it your way:  https://www.bountysource.com/issues/67797215-add-titlealignment-param-to-new-udcard

**Pull request merged**
