### PR TITLE
100% Complete Azure Theme

### PR DESCRIPTION
**Pull request by psDevUK**
Added pagination request on font color also done the same for export grid and refresh to keep in theme, sorted the sub header in side nav not being consistant with the other font color and size. Added default modal color and style, changed icon color for collapsibles so stand out a bit more.  All requests done.

### CODE REVIEW

**Comment by adamdriscoll** [comment]
LGTM!!

**Comment by dtnyc9005** [comment]
These look awesome!, What I noticed is when using these, components are way way up on the top of the screen and get cut off, seems the same is happening in Azure Theme in 2.5.2

**Comment by psDevUK** [comment]
have you tried placing a New-UDRow at the top of your page? This should move everything down a little. If not I can look to see if the CSS can be modified to force a gap from the top navbar. Try placing a new-udrow at the start of your code, see if that solves issue.

**Comment by dtnyc9005** [comment]
Yeah I gave that a shot but same deal, looks like lines 87..98 have something to do with it, when I remove this all is good, but then that breaks the sidebar.

**Comment by psDevUK** [comment]
Ok leave it with me...on lunch right now will post solution once back at my desk. I do apologise

**Comment by dtnyc9005** [comment]
Cool Im having my breakfast now so enjoy ;), just wanted to point out that its happening in 2.5.2 as well.

**Comment by psDevUK** [comment]
Hopefully your breakfast was nice @dtnyc9005 ? Anyways back to the question at hand...so I was thinking the margin-bottom should sort this being applied to either the nav or ud-nav...but I was wrong...So I inspected the element like any good detective would, and found I needed to add the following CSS:-
    'header, nav, section' = @{
      'display' = "block"
      'margin-bottom' = "5%"
    }
For some reason me applying the 'margin-bottom' to any exisiting nav tags didnt work had to add this...now you have space to admire...I will republish the CSS file now to github

**Comment by psDevUK** [comment]
@dtnyc9005 I have now created a PR to upload these changes I provided in the above post I have tested in IE, Fire Fox and Chrome and all 3 browsers I have tested seem to enjoy the change...Pretty sure if you edit Program Files\WindowsPowerShell\Modules\UniversalDashboard\2.5.2\netstandard2.0\Themes and add the lines in it will fix it.

**Comment by dtnyc9005** [comment]
cool thanks! Silly question, am I replacing something or just adding to the bottom of the Azure.psd1 file? I added to the bottom but get the same deal.

**Comment by psDevUK** [comment]
so the very bottom of the Azure.psd1 I just uploaded looks like:-
'.modal'= @{
'z-index' = "9999 !important"
'max-width' = "90% !important"
'max-height' = "90% !important"
'width' = "90% !important"
'color' = "#000"
'background-color' = "#a3a3a3"
}
'header, nav, section' = @{
'display' = "block"
'margin-bottom' = "5%"
}
}
}
 So don't put it right at the bottom it needs to go in the under the "modal" array.

**Comment by psDevUK** [comment]
Or @dtnyc9005 you could go crazy and use the Azure theme, then create a child theme if you still having issues on updating the Azure theme...steps on creating child theme here:-
https://docs.universaldashboard.io/themes#creating-child-themes

**Comment by dtnyc9005** [comment]
Cool @psDevUK that starighten things up for me, the theme is pretty awesome like the roundness in the controls look, do you envision this being an additional theme inside the default theme's folder for the module?

**Comment by psDevUK** [comment]
Hi @dtnyc9005 glad that helped cleared things up for you. I uploaded this Azure theme as a bug with a bounty had been put out on Azure components like Tabs not being consistent with the theme. I had recently spent a long time developing my own rounded theme, so I thought to upload this as a new theme. I've really wanted to contribute to UD and saw this as a good way of doing so. Really happy to hear you like the look and feel of this theme, but @adamdriscoll is the man to ask about the future of UD. I know as end-users we can request enhancements and report issues but he is the man that ultimately makes it happen.

**Comment by dtnyc9005** [comment]
True that! I hear you it takes time for all this to take shape, love UD and the project it is, not a developer by any means, but love getting down and dirty with posh, so by nature those lines of dev/ops are blurred, looking for ways to contribute myself!

**Pull request merged**
