### PR TITLE
Fixes side nav issues and decrease on padding

### PR DESCRIPTION
**Pull request by psDevUK**
Side Nav menu looking sweet on collapsible headers, same  font size, and changed background to lighter blue. Added small amount of padding to images

### CODE REVIEW

**Comment by psDevUK** [comment]
Sorry man, I still left 30px padding at the top of the page, shall I change this to 12px or 2px to get rid of any header space at the top of the dashboard...let me know @adamdriscoll  thanks

**Comment by adamdriscoll** [comment]
Can you fix your diff? I can't tell what changed. I think we still want padding on desktop but not mobile. You can use media queries to do that and detect the screen size: https://www.boldgrid.com/support/wordpress-tutorials/what-is-a-css-media-query/

I think for eliminating the padding altogether, we should make a tight theme.

**Comment by psDevUK** [comment]
Happy to look at default theme again tonight, then make a TightDefault theme...I mean I noticed there is hidden padding on the footer and other elements...this file here though does sort sidenav issues, can do more testing tonight.

**Comment by psDevUK** [comment]
Still got a lot to learn on github....made the top padding 12px to keep inline with the 12px padding I have given the left, right and bottom.  Thanks for posting that link...looks like that is the way to design future CSS themes for UD...although thinking the end CSS file will be bigger as your gonna write it out 3 times, one for mobile, one for tablet and one for desktop...Makes perfect sense to tweak the padding and margins.  Will look at adding this to my list of things to do.

**Comment by psDevUK** [comment]
Sorry @adamdriscoll ended up building a custom component someone requested, so not got round to any theming tonight...did you want this pull request closed and for me to resubmit with the CSS done using the media queries instead before you accept the pull request?

**Comment by adamdriscoll** [comment]
You should be able to just update this existing PR with new changes.

**Pull request closed without merging**
